group=com.masaibar.datastore-inspector
version=1.1.0
protocolArtifact=protocol
runtimeCoreArtifact=runtime-core
runtimePreferencesArtifact=runtime-preferences
runtimeSharedPreferencesArtifact=runtime-shared-preferences
runtimeProtobufArtifact=runtime-protobuf
gradlePluginArtifact=gradle-plugin
